### ISSUE TITLE
Main.java does not compile

### ISSUE THREAD

**Issue by tuitejc** [ameijer/bitcoin_wallet_recovery_tool#1]
I am trying to compile the Main.java file but it cannot find the packages it needs.  I get the following errors

Any ideas?

Main.java

Main.java:24: error: package org.bitcoinj.core does not exist
import org.bitcoinj.core.Address;
                        ^
Main.java:25: error: package org.bitcoinj.core does not exist
import org.bitcoinj.core.ECKey;
                        ^
Main.java:26: error: package org.bitcoinj.params does not exist
import org.bitcoinj.params.MainNetParams;
                          ^
Main.java:27: error: package org.bitcoinj.store does not exist
import org.bitcoinj.store.BlockStoreException;
                         ^
Main.java:28: error: package org.json does not exist
import org.json.JSONArray;
               ^
Main.java:29: error: package org.json does not exist
import org.json.JSONException;
               ^
Main.java:30: error: package org.json does not exist
import org.json.JSONObject;
               ^
Main.java:32: error: package com.google.common.collect does not exist
import com.google.common.collect.Lists;
                                ^
Main.java:33: error: package com.google.zxing does not exist
import com.google.zxing.BarcodeFormat;
                       ^
Main.java:34: error: package com.google.zxing does not exist
import com.google.zxing.EncodeHintType;
                       ^
Main.java:35: error: package com.google.zxing does not exist
import com.google.zxing.WriterException;
                       ^
Main.java:36: error: package com.google.zxing.common does not exist
import com.google.zxing.common.BitMatrix;
                              ^
Main.java:37: error: package com.google.zxing.qrcode does not exist
import com.google.zxing.qrcode.QRCodeWriter;
                              ^
Main.java:38: error: package com.google.zxing.qrcode.decoder does not exist
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
                                      ^
Main.java:77: error: cannot find symbol
                        t

**Comment by ameijer** [comment]
hi there. you will need to use maven to build this project. the pom.xml file has those dependencies you need.

**Comment by tuitejc** [comment]
Thanks!  I had someone help me that knew what they were doing and got it to work!
