### ISSUE TITLE
cant execute

### ISSUE THREAD

**Issue by edbessa333** [ameijer/bitcoin_wallet_recovery_tool#16]
Hi, ive installed maven and java and its all working, but I have this wallet.dat file and I don't know how can I use the program, but I need to use it on this wallet, I don't have experience in this... please help!

**Comment by edbessa333** [comment]
it says: The software will prompt??? it doesn't prompt me for the file.... how can I do this?

**Comment by ameijer** [comment]
here are some guides on how to run things in maven: https://stackoverflow.com/questions/57980136/how-to-run-java-program-using-maven

Thanks!

**Comment by edbessa333** [comment]
can you give me an example to how to do this on a wallet.dat file
