### ISSUE TITLE
Using a java file

### ISSUE THREAD

**Issue by jatoshi** [ameijer/bitcoin_wallet_recovery_tool#3]
Hi Alex, Is there an easy way to use this java program? Ive never used java before and I think this tool might just save my life... Do I just run the java file on windows 10? Or do I need to run on a different platform? Sorry for all the Qs im not a developer.. But would be great if I could recover my corrupt btc wallets from bitcoin core qt.
Thanks!

**Comment by ameijer** [comment]
Hi there! Thanks for your interest in my software. 

You will need to install maven, then compile an executable jar from that. Alternatively, you could use an IDE like eclipse or intellij, and run it right from that. You will have to provide command line arguments pointing to the file you want to decrypt, etc etc. 

If you want, you could sponsor a release mechanism for 0.023 BTC (address: 12mfJxZmkSjiNGiLyTpXhVJAANiDaVbkE5), I would release an executable jar download-able here on github, runs on windows, and will have a decent help menu for the command line arguments. Or, you do it yourself and learn about programming. I welcome pull requests! Re - open this issue if you are interested.
