### ISSUE TITLE
We need longer delays, I keep getting rate limited. Server returned HTTP response code: 429 

### ISSUE THREAD

**Issue by YouWishh** [ameijer/bitcoin_wallet_recovery_tool#9]
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 429 for URL: https://blockchain.info/multiaddr

On blockchain they say rate limit is 1 request per 10 seconds. Looking at source it seems this program does 1 request every 3 seconds.

**Comment by ameijer** [comment]
ok. they seem to be changing that a lot, so I'll make it configurable I suppose

**Comment by ameijer** [comment]
fixes in https://github.com/ameijer/bitcoin_wallet_recovery_tool/releases/tag/v1.1.0
